# Pandas 数据清洗

数据清洗是对一些没有用的数据进行处理的过程。

很多数据集存在数据缺失、数据格式错误、错误数据或重复数据的情况，如果要使数据分析更加准确，就需要对这些没有用的数据进行处理。

## 数据清洗与预处理的常见步骤：

- **缺失值处理**：识别并填补缺失值，或删除含缺失值的行/列。

- **重复数据处理**：检查并删除重复数据，确保每条数据唯一。

- **异常值处理**：识别并处理异常值，如极端值、错误值。

- **数据格式转换**：转换数据类型或进行单位转换，如日期格式转换。

- **标准化与归一化**：对数值型数据进行标准化（如 Z-score）或归一化（如 Min-Max）。

- **类别数据编码**：将类别变量转换为数值形式，常见方法包括 One-Hot 编码和标签编码。

- **文本处理**：对文本数据进行清洗，如去除停用词、词干化、分词等。

- **数据抽样**：从数据集中抽取样本，或通过过采样/欠采样处理类别不平衡。

- **特征工程**：创建新特征、删除不相关特征、选择重要特征等。

# Pandas 清洗空值

如果我们删除包含空字段的行，可以使用 dropna() 方法，语法格式如下：

```
DataFrame.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
```

## 参数说明：

- **axis**：默认为 0，表示逢空值剔除整行，如果设置参数 axis＝1 表示逢空值去掉整列。

- **how**：默认为 'any' 如果一行（或一列）里任何一个数据有出现 NA 就去掉整行，如果设置 how='all' 一行（或列）都是 NA 才去掉这整行。

- **thresh**：设置需要多少非空值的数据才可以保留下来的。

- **subset**：设置想要检查的列。如果是多个列，可以使用列名的 list 作为参数。

- **inplace**：如果设置 True，将计算得到的值直接覆盖之前的值并返回 None，修改的是源数据。

# 常用方法及说明

数据清洗与预处理的常见方法：

| 操作 | 方法/步骤 | 说明 | 常用函数/方法 |
|------|-----------|------|---------------|
| 缺失值处理 | 填充缺失值 | 使用指定的值（如均值、中位数、众数等）填充缺失值。 | df.fillna(value) |
| | 删除缺失值 | 删除包含缺失值的行或列。 | df.dropna() |
| 重复数据处理 | 删除重复数据 | 删除 DataFrame 中的重复行。 | df.drop_duplicates() |
| 异常值处理 | 异常值检测（基于统计方法） | 通过 Z-score 或 IQR 方法识别并处理异常值。 | 自定义函数（如基于 Z-score 或 IQR）|
| | 替换异常值 | 使用合适的值（如均值或中位数）替换异常值。 | 自定义函数（如替换异常值）|
| 数据格式转换 | 转换数据类型 | 将数据类型从一个类型转换为另一个类型，如将字符串转换为日期。 | df.astype() |
| | 日期时间格式转换 | 转换字符串或数字为日期时间类型。 | pd.to_datetime() |
| 标准化与归一化 | 标准化 | 将数据转换为均值为0，标准差为1的分布。 | StandardScaler() |
| | 归一化 | 将数据缩放到指定的范围（如 [0, 1]）。 | MinMaxScaler() |
| 类别数据编码 | 标签编码 | 将类别变量转换为整数形式。 | LabelEncoder() |
| | 独热编码（One-Hot Encoding） | 将每个类别转换为一个新的二进制特征。 | pd.get_dummies() |
| 文本数据处理 | 去除停用词 | 从文本中去除无关紧要的词，如 "the" 、 "is" 等。 | 自定义函数（基于 nltk 或 spaCy）|
| | 词干化与词形还原 | 提取词干或恢复单词的基本形式。 | nltk.stem.PorterStemmer() |
| | 分词 | 将文本分割成单词或子词。 | nltk.word.tokenize() |
| 数据抽样 | 随机抽样 | 从数据中随机抽取一定比例的样本。 | df.sample() |
| | 上采样与下采样 | 通过过采样（复制少数类样本）或欠采样（减少多数类样本）来平衡数据集中的类别分布。 | SMOTE()（上采样）； RandomUnderSampler()（下采样）|
| 特征工程 | 特征选择 | 选择对目标变量有影响的特征，去除冗余或无关特征。 | SelectKBest() |
| | 特征提取 | 从原始数据中创建新的特征，提升模型的预测能力。 | PolynomialFeatures() |
| | 特征缩放 | 对数值特征进行缩放，使其具有相同的量级。 | MinMaxScaler() 、 StandardScaler() |
| | 类别特征映射 | 特征映射 | 将类别变量映射为对应的数字编码。 | 自定义映射函数 |
| 数据合并与连接 | 合并数据 | 将多个 DataFrame 按照某些列合并在一起，支持内连接、外连接、左连接、右连接等。 | pd.merge() |
| | 连接数据 | 将多个 DataFrame 进行行或列拼接。 | pd.concat() |
| 数据重塑 | 数据透视表 | 将数据根据某些维度进行分组并计算聚合结果。 | pd.pivot_table() |
| | 数据变形 | 改变数据的形状，如从长格式转为宽格式或从宽格式转为长格式。 | df.melt() 、 df.pivot() |
| 数据类型转换与处理 | 字符串处理 | 对字符串数据进行处理，如去除空格、转换大小写等。 | str.replace() 、 str.upper() 等 |
| | 分组计算 | 按照某个特征分组后进行聚合计算。 | df.groupby() |
| 缺失值预测填充 | 使用模型预测填充缺失值 | 使用机器学习模型（如回归模型）预测缺失值，并填充缺失数据。 | 自定义模型（如 sklearn.linear_model.LinearRegression）|
| 时间序列处理 | 时间序列缺失值填充 | 使用时间序列的方法（如前向填充、后向填充）填充缺失值。 | df.fillna(method='ffill') |
| | 滚动窗口计算 | 使用滑动窗口进行时间序列数据的统计计算（如均值、标准差等）。 | df.rolling(window=5).mean() |
| 数据转换与映射 | 数据映射与替换 | 将数据中的某些值替换为其他值。 | df.replace() |

In [450]:
# 通过 isnull() 方法判断各个单元格是否为空
import pandas as pd
import numpy as np

df = pd.read_csv('property-data.csv')

print (df['NUM_BEDROOMS'])

print("\n")

print (df['NUM_BEDROOMS'].isnull())

print("\n")

0      3
1      3
2    NaN
3      1
4      3
5    NaN
6      2
7      1
8     na
Name: NUM_BEDROOMS, dtype: object


0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
Name: NUM_BEDROOMS, dtype: bool

In [451]:
# 我们看到 Pandas 把 n/a 和 NA 当作空数据，na 不是空数据，不符合我们要求，我们可以指定空数据类型：
missing_value = ["n/a" , "na" , "--"]
df = pd.read_csv('property-data.csv', na_values = missing_value)
print (df['NUM_BEDROOMS'])

print("\n")

print (df['NUM_BEDROOMS'].isnull())

0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    1.0
8    NaN
Name: NUM_BEDROOMS, dtype: float64


0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
Name: NUM_BEDROOMS, dtype: bool

In [452]:
# 演示删除包含空数据的行
# 默认情况下，dropna() 方法返回一个新的 DataFrame，不会修改源数据。
# 如果要修改源数据，需要设置 inplace 参数为 True
df = pd.read_csv('property-data.csv')

new_df = df.dropna()

print(new_df.to_string())

           PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [453]:
df = pd.read_csv('property-data.csv')
df.dropna(inplace = True)
print(df.to_string())

           PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [454]:
# 移除指定列中包含空数据的行
df = pd.read_csv('property-data.csv')
df.dropna(subset = ['ST_NUM'], inplace = True)
print(df.to_string())

           PID  ST_NUM    ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0     PUTNAM            Y            3        1  1000
1  100002000.0   197.0  LEXINGTON            N            3      1.5    --
3  100004000.0   201.0   BERKELEY           12            1      NaN   700
4          NaN   203.0   BERKELEY            Y            3        2  1600
5  100006000.0   207.0   BERKELEY            Y          NaN        1   800
7  100008000.0   213.0    TREMONT            Y            1        1   NaN
8  100009000.0   215.0    TREMONT            Y           na        2  1800

In [455]:
# 利用 fillna() 方法填充空数据
df = pd.read_csv('property-data.csv')

df.fillna(12345 , inplace = True)
print(df.to_string())

           PID   ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH  SQ_FT
0  100001000.0    104.0      PUTNAM            Y            3        1   1000
1  100002000.0    197.0   LEXINGTON            N            3      1.5     --
2  100003000.0  12345.0   LEXINGTON            N        12345        1    850
3  100004000.0    201.0    BERKELEY           12            1    12345    700
4      12345.0    203.0    BERKELEY            Y            3        2   1600
5  100006000.0    207.0    BERKELEY            Y        12345        1    800
6  100007000.0  12345.0  WASHINGTON        12345            2   HURLEY    950
7  100008000.0    213.0     TREMONT            Y            1        1  12345
8  100009000.0    215.0     TREMONT            Y           na        2   1800

In [456]:
# 指定某个列填充空数据
df = pd.read_csv('property-data.csv')

df.fillna({'ST_NUM': 12345, 'NUM_BEDROOMS': 0}, inplace = True)
print(df.to_string())

           PID   ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0    104.0      PUTNAM            Y            3        1  1000
1  100002000.0    197.0   LEXINGTON            N            3      1.5    --
2  100003000.0  12345.0   LEXINGTON            N            0        1   850
3  100004000.0    201.0    BERKELEY           12            1      NaN   700
4          NaN    203.0    BERKELEY            Y            3        2  1600
5  100006000.0    207.0    BERKELEY            Y            0        1   800
6  100007000.0  12345.0  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0    213.0     TREMONT            Y            1        1   NaN
8  100009000.0    215.0     TREMONT            Y           na        2  1800

In [457]:
# 替换空单元格的常用方法是计算列的均值、中位数值或众数
# Pandas使用 mean()、median() 和 mode() 方法计算列的均值（所有值加起来的平均值）、中位数值（排序后排在中间的数）和众数（出现频率最高的数）。

# 使用 mean() 方法填充空数据
df = pd.read_csv('property-data.csv')
x = df['ST_NUM'].mean()                     # 计算 ST_NUM 列的均值

df.fillna({'ST_NUM' : x} , inplace = True)

print(df.to_string())

           PID      ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0  104.000000      PUTNAM            Y            3        1  1000
1  100002000.0  197.000000   LEXINGTON            N            3      1.5    --
2  100003000.0  191.428571   LEXINGTON            N          NaN        1   850
3  100004000.0  201.000000    BERKELEY           12            1      NaN   700
4          NaN  203.000000    BERKELEY            Y            3        2  1600
5  100006000.0  207.000000    BERKELEY            Y          NaN        1   800
6  100007000.0  191.428571  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0  213.000000     TREMONT            Y            1        1   NaN
8  100009000.0  215.000000     TREMONT            Y           na        2  1800

In [458]:
# 使用 median() 方法填充空数据  
df = pd.read_csv('property-data.csv')
x = df['ST_NUM'].median()                     # 计算 ST_NUM 列的中位数

df.fillna({'ST_NUM' : x} , inplace = True)

print(df.to_string())

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0   203.0   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0   203.0  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [459]:
# 使用 mode() 方法填充空数据
df = pd.read_csv('property-data.csv')
x = df['ST_NUM'].mode()[0]                     # 计算 ST_NUM 列的众数 , [0] 表示取第一个众数

df.fillna({'ST_NUM' : x} , inplace = True)

print(df.to_string())

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0   104.0   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0   104.0  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y            1        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

In [460]:
# 清洗格式错误的数据

# 第三个日期格式错误
date = {
    'Date' : ['2023-01-01', '2023-02-02', '2023-03-03', '20230404'],
    'Duration' : [10, 20, 30, 40]
}

df = pd.DataFrame(date , index = ['Day1' , 'Day2' , 'Day3' , 'Day4'])
df['Date'] = pd.to_datetime(df['Date'] , format='mixed')                            # format='mixed' 表示自动识别日期格式
print(df.to_string())

           Date  Duration
Day1 2023-01-01        10
Day2 2023-02-02        20
Day3 2023-03-03        30
Day4 2023-04-04        40

In [461]:
# 替换错误年龄的数据
person = {
  "name": ['Google', 'Runoob' , 'Taobao'],
  "age": [50, 40, 12345]    # 12345 年龄数据是错误的
}

df = pd.DataFrame(person)

# 统计年龄大于 100 的人数
print((df['age'] > 100).sum())

print("\n")

# 展示 bool 类型的 Series
print(df['age'] > 100)

print('\n')

# 展示年龄大于 100 的行
print(df[df['age'] > 100])

# 替换年龄大于 100 的数据为 np.NAN
df.loc[df['age'] > 100 , 'age'] = np.NAN

# 计算年龄的平均值
x = df['age'].mean()

print('\n')

# 将缺失值填充为平均值
df.loc[df['age'].isnull() , 'age'] = x
df

1


0    False
1    False
2     True
Name: age, dtype: bool


     name    age
2  Taobao  12345

     name   age
0  Google  50.0
1  Runoob  40.0
2  Taobao  45.0

In [462]:
# 设置条件语句
# 将 age 大于 120 的数据设置为 120
person = {
  "name": ['Google', 'Runoob' , 'Taobao'],
  "age": [50, 200, 12345]    
}

df = pd.DataFrame(person)
df.loc[df['age'] > 120 , 'age'] = 120
df

     name  age
0  Google   50
1  Runoob  120
2  Taobao  120

In [463]:
# 将错误数据的行删除
df.drop(df[df['age'] >= 120].index, inplace=True)
df

     name  age
0  Google   50

In [464]:
# Pandas 清洗重复数据
# 如果我们要清洗重复数据，可以使用 duplicated() 和 drop_duplicates() 方法。
# 如果对应的数据是重复的，duplicated() 会返回 True，否则返回 False。
person = {
  "name": ['Google', 'Runoob', 'Runoob', 'Taobao'],
  "age": [50, 40, 40, 23]  
}

df = pd.DataFrame(person)

# 重复返回 True
print(df.duplicated())

print("\n")

# 展示重复的行
print(df[df.duplicated()])

print("\n")

# 展示不重复的行
print(df[~df.duplicated()])

0    False
1    False
2     True
3    False
dtype: bool


     name  age
2  Runoob   40


     name  age
0  Google   50
1  Runoob   40
3  Taobao   23

In [465]:
# 删除重复数据，可以直接使用drop_duplicates() 方法
persons = {
  "name": ['Google', 'Runoob', 'Runoob', 'Taobao'],
  "age": [50, 40, 40, 23]  
}

df = pd.DataFrame(persons)

df.drop_duplicates(inplace = True)
print(df)

     name  age
0  Google   50
1  Runoob   40
3  Taobao   23

In [466]:
# 填充缺失值
# 示例数据
data = {'Name': ['Alice', 'Bob', 'Charlie', None],
        'Age': [25, 30, None, 35],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)

df.fillna({'Age' : df['Age'].mean() , 'Name' : 'Unknown'} , inplace=True)

print(df)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  30.0      Chicago
3  Unknown  35.0      Houston

In [467]:
# 独热编码
# 独热编码是将分类变量转换为二进制向量的过程，每个类别对应一个二进制位。
# 有 N 个不同的类别，就会生成 N 个二进制位。仅对应位置为 1，其他位置为 0。
# 独热编码的优势在于可以将分类变量转换为数值变量，方便进行机器学习模型的训练。
# 示例数据
data = {'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

df = pd.DataFrame(data)

# 对 "City" 列进行 One-Hot 编码
df_encoded = pd.get_dummies(df, columns=['City'])

print(df_encoded)

   City_Chicago  City_Houston  City_Los Angeles  City_New York
0         False         False             False           True
1         False         False              True          False
2          True         False             False          False
3         False          True             False          False

In [468]:
# 数据标准化
from sklearn.preprocessing import StandardScaler
# 示例数据
data = {'Age': [25, 30, 35, 40, 45],
        'Salary': [50000, 60000, 70000, 80000, 90000]}

df = pd.DataFrame(data)

# 标准化数据
scaler = StandardScaler()
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])
print(df)

        Age    Salary
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214